---
- name: Para o IIS
  hosts: all
  gather_facts: no
  tasks:
    - name: Executar PowerShell para parar o IIS
      win_shell: |
        Stop-Service -Name 'W3SVC' -Force
      register: command_result

    - name: Verificar se o comando foi bem-sucedido
      debug:
        msg: "Comando executado com sucesso!"
      when: command_result.rc == 0