- name: Ajuste de permissão Linux
  hosts: all
  become: true
  tasks:

    - name: Incluir usuário do sysadmin no grupo de sudoers
      shell: usermod -aG sudo sysadmin
      register: state
    - name: Status da execução
      debug:
        var: state.stdout_lines

    - name: Valida quais grupos o usuário está
      shell: id sysadmin
      register: id
    - name: Status da execução
      debug:
        var: id.stdout_lines